//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odintsov.Accounts.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Evaluations = new HashSet<Evaluation>();
            this.EvaluationsReviews = new HashSet<Evaluation>();
            this.Team = new HashSet<Account>();
            this.EvaluationsManages = new HashSet<Evaluation>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public string Salt { get; set; }
        public string FullName { get; set; }
        public string Sex { get; set; }
        public string Region { get; set; }
        public string MicroRegion { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public Nullable<Role> Role { get; set; }
        public string Guid { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string ManagerFullName { get; set; }
        public Nullable<double> LastEvaluationPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> EvaluationsReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Team { get; set; }
        public virtual Account Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> EvaluationsManages { get; set; }
    }
}
