//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odintsov.Accounts.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationValue
    {
        public int Id { get; set; }
        public Nullable<int> Competency { get; set; }
        public Nullable<int> Indicator { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> ReviewValue { get; set; }
        public int EvaluationId { get; set; }
        public Nullable<double> ManagerValue { get; set; }
    
        public virtual Evaluation Evaluation { get; set; }
    }
}
